//Groups
export const SELECT_GROUP = "SELECT_GROUP";

export const FETCH_GROUPS_START = "FETCH_GROUPS_START";
export const FETCH_GROUPS_SUCCESS = "FETCH_GROUPS_SUCCESS";
export const FETCH_GROUPS_FAIL = "FETCH_GROUPS_FAIL";

export const CREATE_GROUP_START = "CREATE_GROUP_START";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAIL = "CREATE_GROUP_FAIL";

//Posts
export const SELECT_POST = "SELECT_POST";

export const FETCH_POSTS_START = "FETCH_POSTS_START";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL";

export const MAKE_POST_START = "MAKE_POST_START";
export const MAKE_POST_SUCCESS = "MAKE_POST_SUCCESS";
export const MAKE_POST_FAIL = "MAKE_POST_FAIL";
