export const SELECT_GROUP = "SELECT_GROUP";

export const FETCH_GROUPS_START = "FETCH_GROUPS_START";
export const FETCH_GROUPS_SUCCESS = "FETCH_GROUPS_SUCCESS";
export const FETCH_GROUPS_FAIL = "FETCH_GROUPS_FAIL";

export const CREATE_GROUP_START = "CREATE_GROUP_START";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAIL = "CREATE_GROUP_FAIL";
