const token = {
  token:
    "BQBLK6rYhzLE-iC1Kk-0xvKOkwcQbJfxAgGC72QWOghzaBxUmV2_yvPOOGPRyrlKWhJl8KZs_ziTka6KuuGtn9xTPR_5kUNVoPxfYe0niQ5X5CZRIHVlS2EgUwpw2G7kecwJNTQ21cyOxslNrQL3MEdmaYcRvQ",
  item: {
    album: {
      album_type: "album",
      artists: [
        {
          external_urls: {
            spotify: "https://open.spotify.com/artist/3qnGvpP8Yth1AqSBMqON5x"
          },
          href: "https://api.spotify.com/v1/artists/3qnGvpP8Yth1AqSBMqON5x",
          id: "3qnGvpP8Yth1AqSBMqON5x",
          name: "Leon Bridges",
          type: "artist",
          uri: "spotify:artist:3qnGvpP8Yth1AqSBMqON5x"
        }
      ],
      available_markets: [
        "AD",
        "AE",
        "AR",
        "AT",
        "AU",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "CA",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "SA",
        "SE",
        "SG",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "US",
        "UY",
        "VN",
        "ZA"
      ],
      external_urls: {
        spotify: "https://open.spotify.com/album/7J9fifadXb0PPSBWXctbi8"
      },
      href: "https://api.spotify.com/v1/albums/7J9fifadXb0PPSBWXctbi8",
      id: "7J9fifadXb0PPSBWXctbi8",
      images: [
        {
          height: 640,
          url:
            "https://i.scdn.co/image/ab67616d0000b273a47ee7a49c53ccdcb38dc874",
          width: 640
        },
        {
          height: 300,
          url:
            "https://i.scdn.co/image/ab67616d00001e02a47ee7a49c53ccdcb38dc874",
          width: 300
        },
        {
          height: 64,
          url:
            "https://i.scdn.co/image/ab67616d00004851a47ee7a49c53ccdcb38dc874",
          width: 64
        }
      ],
      name: "Good Thing",
      release_date: "2018-05-04",
      release_date_precision: "day",
      total_tracks: 10,
      type: "album",
      uri: "spotify:album:7J9fifadXb0PPSBWXctbi8"
    },
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/3qnGvpP8Yth1AqSBMqON5x"
        },
        href: "https://api.spotify.com/v1/artists/3qnGvpP8Yth1AqSBMqON5x",
        id: "3qnGvpP8Yth1AqSBMqON5x",
        name: "Leon Bridges",
        type: "artist",
        uri: "spotify:artist:3qnGvpP8Yth1AqSBMqON5x"
      }
    ],
    available_markets: [
      "AD",
      "AE",
      "AR",
      "AT",
      "AU",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JO",
      "JP",
      "KW",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PS",
      "PT",
      "PY",
      "QA",
      "RO",
      "SA",
      "SE",
      "SG",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "US",
      "UY",
      "VN",
      "ZA"
    ],
    disc_number: 1,
    duration_ms: 240600,
    explicit: false,
    external_ids: { isrc: "USSM11800493" },
    external_urls: {
      spotify: "https://open.spotify.com/track/1Omt5bfz1tZUCqd26HxbS0"
    },
    href: "https://api.spotify.com/v1/tracks/1Omt5bfz1tZUCqd26HxbS0",
    id: "1Omt5bfz1tZUCqd26HxbS0",
    is_local: false,
    name: "Beyond",
    popularity: 70,
    preview_url:
      "https://p.scdn.co/mp3-preview/c2ec433b724bbd36f0761809d78ec46fc272da55?cid=fe759877d178489e98e0856714dd04c5",
    track_number: 4,
    type: "track",
    uri: "spotify:track:1Omt5bfz1tZUCqd26HxbS0"
  },
  is_playing: true,
  progress_ms: 14201
};
